### ISSUE TITLE
New crates.io Release?

### ISSUE THREAD

**Issue by ra-kete** [smart-leds-rs/ws2812-spi-rs#10]
The last release on crates.io (0.2.0) has been nearly a year ago. Meanwhile there have been a few significant changes, it seems. At least in my case, the current crates.io release doesn't work at all, while the master branch runs flawlessly.

So can we get a new release please?

**Comment by david-sawatzke** [comment]
Sure, fixed with https://github.com/smart-leds-rs/ws2812-spi-rs/commit/fac281eb57b5f72c48e368682645e3b0bd5b4b83
